title: D&D Event Announcer Official
theme: jekyll-theme-cayman
description: The official website for the D&D Event Announcer bot â€” helping you manage your tabletop campaigns with ease.
author: anaSTHENIS
